/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BieresRouteImport } from './routes/bieres'
import { Route as ChampagnesRouteImport } from './routes/champagnes'
import { Route as CocktailsRouteImport } from './routes/cocktails'
import { Route as ShishaRouteImport } from './routes/shisha'
import { Route as SoftsRouteImport } from './routes/softs'
import { Route as VinsRouteImport } from './routes/vins'
import { Route as VodkasLiqueursRouteImport } from './routes/vodkas-liqueurs'
import { Route as WhiskiesCognacsRouteImport } from './routes/whiskies-cognacs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BieresRoute = BieresRouteImport.update({
  id: '/bieres',
  path: '/bieres',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampagnesRoute = ChampagnesRouteImport.update({
  id: '/champagnes',
  path: '/champagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const CocktailsRoute = CocktailsRouteImport.update({
  id: '/cocktails',
  path: '/cocktails',
  getParentRoute: () => rootRouteImport,
} as any)
const ShishaRoute = ShishaRouteImport.update({
  id: '/shisha',
  path: '/shisha',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftsRoute = SoftsRouteImport.update({
  id: '/softs',
  path: '/softs',
  getParentRoute: () => rootRouteImport,
} as any)
const VinsRoute = VinsRouteImport.update({
  id: '/vins',
  path: '/vins',
  getParentRoute: () => rootRouteImport,
} as any)
const VodkasLiqueursRoute = VodkasLiqueursRouteImport.update({
  id: '/vodkas-liqueurs',
  path: '/vodkas-liqueurs',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiskiesCognacsRoute = WhiskiesCognacsRouteImport.update({
  id: '/whiskies-cognacs',
  path: '/whiskies-cognacs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bieres': typeof BieresRoute
  '/champagnes': typeof ChampagnesRoute
  '/cocktails': typeof CocktailsRoute
  '/shisha': typeof ShishaRoute
  '/softs': typeof SoftsRoute
  '/vins': typeof VinsRoute
  '/vodkas-liqueurs': typeof VodkasLiqueursRoute
  '/whiskies-cognacs': typeof WhiskiesCognacsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bieres': typeof BieresRoute
  '/champagnes': typeof ChampagnesRoute
  '/cocktails': typeof CocktailsRoute
  '/shisha': typeof ShishaRoute
  '/softs': typeof SoftsRoute
  '/vins': typeof VinsRoute
  '/vodkas-liqueurs': typeof VodkasLiqueursRoute
  '/whiskies-cognacs': typeof WhiskiesCognacsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bieres': typeof BieresRoute
  '/champagnes': typeof ChampagnesRoute
  '/cocktails': typeof CocktailsRoute
  '/shisha': typeof ShishaRoute
  '/softs': typeof SoftsRoute
  '/vins': typeof VinsRoute
  '/vodkas-liqueurs': typeof VodkasLiqueursRoute
  '/whiskies-cognacs': typeof WhiskiesCognacsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bieres'
    | '/champagnes'
    | '/cocktails'
    | '/shisha'
    | '/softs'
    | '/vins'
    | '/vodkas-liqueurs'
    | '/whiskies-cognacs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bieres'
    | '/champagnes'
    | '/cocktails'
    | '/shisha'
    | '/softs'
    | '/vins'
    | '/vodkas-liqueurs'
    | '/whiskies-cognacs'
  id:
    | '__root__'
    | '/'
    | '/bieres'
    | '/champagnes'
    | '/cocktails'
    | '/shisha'
    | '/softs'
    | '/vins'
    | '/vodkas-liqueurs'
    | '/whiskies-cognacs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BieresRoute: typeof BieresRoute
  ChampagnesRoute: typeof ChampagnesRoute
  CocktailsRoute: typeof CocktailsRoute
  ShishaRoute: typeof ShishaRoute
  SoftsRoute: typeof SoftsRoute
  VinsRoute: typeof VinsRoute
  VodkasLiqueursRoute: typeof VodkasLiqueursRoute
  WhiskiesCognacsRoute: typeof WhiskiesCognacsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bieres': {
      id: '/bieres'
      path: '/bieres'
      fullPath: '/bieres'
      preLoaderRoute: typeof BieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champagnes': {
      id: '/champagnes'
      path: '/champagnes'
      fullPath: '/champagnes'
      preLoaderRoute: typeof ChampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocktails': {
      id: '/cocktails'
      path: '/cocktails'
      fullPath: '/cocktails'
      preLoaderRoute: typeof CocktailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shisha': {
      id: '/shisha'
      path: '/shisha'
      fullPath: '/shisha'
      preLoaderRoute: typeof ShishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softs': {
      id: '/softs'
      path: '/softs'
      fullPath: '/softs'
      preLoaderRoute: typeof SoftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vins': {
      id: '/vins'
      path: '/vins'
      fullPath: '/vins'
      preLoaderRoute: typeof VinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vodkas-liqueurs': {
      id: '/vodkas-liqueurs'
      path: '/vodkas-liqueurs'
      fullPath: '/vodkas-liqueurs'
      preLoaderRoute: typeof VodkasLiqueursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiskies-cognacs': {
      id: '/whiskies-cognacs'
      path: '/whiskies-cognacs'
      fullPath: '/whiskies-cognacs'
      preLoaderRoute: typeof WhiskiesCognacsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BieresRoute: BieresRoute,
  ChampagnesRoute: ChampagnesRoute,
  CocktailsRoute: CocktailsRoute,
  ShishaRoute: ShishaRoute,
  SoftsRoute: SoftsRoute,
  VinsRoute: VinsRoute,
  VodkasLiqueursRoute: VodkasLiqueursRoute,
  WhiskiesCognacsRoute: WhiskiesCognacsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
